name: node.js Package

on:
  push:
    branches:
      - main
jobs:
  publish-gpr:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version : 16
          registry-url: https://npm.pkg.github.com/
          scope: '@armennag'
      - run: npm install
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
  job2:
    runs-on: ubuntu-latest
    needs: publish-gpr
    steps:
    - uses: actions/delete-package-versions@v2
      with:
          package-name: 'test-package'
          toke : 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
    - uses: actions/delete-package-versions@v2
      with:
          package-name: test-package
          toke : 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
    - uses: actions/delete-package-versions@v2
      with:
          package-name: '/test-package'
          toke : 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
    - uses: actions/delete-package-versions@v2
      with:
          package-name: 'armennag/test-package'
          toke : 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
    - uses: actions/delete-package-versions@v2
      with:
          package-name: '@armennag/test-package'
          toke : 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
    - uses: actions/delete-package-versions@v2
      with:
          package-name: armennag/test-package
          toke : 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 
    - uses: actions/delete-package-versions@v2
      with:
          package-name: "@armennag/test-package"
          toke : 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 
    - uses: smartsquaregmbh/delete-old-packages@v0.5.0
      with:
        names: |
              @armennag/test-package@1.0.5
              test-package
    - name: Remove package versions
      id: remove-package-versions
      uses: epitomeglobal/remove-package-versions@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    

