name: node.js Package

on:
  push:
    branches:
      - main
jobs:
  publish-gpr:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version : 16
          registry-url: https://npm.pkg.github.com/
          scope: '@armennag'
      - run: npm install
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
  deletePackage:
    runs-on: ubuntu-latest
    needs: publish-gpr
    steps:
    - uses: WPMedia/delete-github-package-versions@v0.4.10
      with:
        names: |
          keep: 5
          'test-package'
          
